ARC 94 + Style fixes
ArchivistProject/archivist-clipper-chrome pull request #3
Opened 2017-01-30 04:25 UTC by Redwards34

Make Style fixes as per ESlint
Send message to SingleCore and save the clipped page response
Add Eslint and npm package list

2017-01-31 23:13 UTC, mr2ert requested changes
Lets also add an explanation of what ARC-94 is in the title.  Otherwise, looks good. :shipit:

2017-01-31 23:13 UTC, mr2ert commented on package.json
> +    "eslint-plugin-react": "^6.9.0"
We don't need the react plugin for this repo since we aren't using react in the plugin (unless you are planning to).  

Have you seen this? https://ignat-zakrevsky.github.io/javascript/codeship/karma/eslint/2015/11/18/extension-codeship-testing.html

2017-01-31 23:13 UTC, mr2ert commented on scripts/popup.js
> +const SINGLE_FILE_CORE_EXT_ID = 'jemlklgaibiijojffihnhieihhagocma';
Instead of putting this all in one giant file, can we start splitting this apart into logical sub-files?

2017-01-31 23:13 UTC, mr2ert commented on scripts/popup.js
> +const SINGLE_FILE_CORE_EXT_ID = 'jemlklgaibiijojffihnhieihhagocma';
Also, are we going to require them to install the 'core' extension alongside our extension?  The single file related stuff is a good candidate.

2017-01-31 23:13 UTC, mr2ert commented on scripts/popup.js
> +  xhr.open('POST', 'http://localhost:3000/public/documents', true);
If we are using jquery, lets also use their REST api because it is way more readable: https://api.jquery.com/jquery.post/

2017-01-31 23:13 UTC, mr2ert commented on scripts/popup.js
> +      //text: metadataField.name
Remove this comment as it is leftover code?

2017-01-31 23:13 UTC, mr2ert commented on scripts/popup.js
> +    chrome.downloads.download({url:url, filename: "archived-page.html"});
Let's get the result here and print `archived-page.html` out to the console instead as this is closer to what we ultimately need to do.

2017-01-31 23:22 UTC, mr2ert commented
Let's also add `"lint": "`npm bin`/eslint src"` as a `script` in `packages.json` and a `.travis.yml` file with:
```
language: node_js
node_js:
  - "node"
script: 
  - "npm run lint"
```

2017-01-31 23:24 UTC, mr2ert commented on package.json
> +    "eslint-plugin-react": "^6.9.0"
Also Tyler's eslint file: https://github.com/ArchivistProject/archivist-web/blob/master/.eslintrc.js

2017-01-31 23:31 UTC, mr2ert commented on scripts/popup.js
> +const SINGLE_FILE_CORE_EXT_ID = 'jemlklgaibiijojffihnhieihhagocma';
For splitting it apart: http://stackoverflow.com/a/27840713/2336149

2017-01-31 23:35 UTC, Redwards34 commented on package.json
> +    "eslint-plugin-react": "^6.9.0"
React required simply for the air bnb rules.

2017-01-31 23:35 UTC, Redwards34 commented on scripts/popup.js
> +const SINGLE_FILE_CORE_EXT_ID = 'jemlklgaibiijojffihnhieihhagocma';
Next task will be to experiment with bringing in core extension.

2017-02-01 05:03 UTC, mr2ert approved these changes

2017-02-02 21:42 UTC, merged